#服务端口
server:
  port: 8012
#服务名
spring:
  application:
    name: eureka-server-clustered
eureka:
  instance:
    hostname: 192.168.0.25
    prefer-ip-address: true
  client: 
      register-with-eureka: true #是否注册自身到eureka服务器
      fetch-registry: false
      serviceUrl:
        defaultZone: http://192.168.0.26:8013/eureka/,http://192.168.0.24:8011/eureka/
   #设置eureka服务器所在的地址，注册服务需要依赖这个地址
  server:
    registry-sync-retry-wait-ms: 500 #服务器注册表同步重试等待毫秒
    a-sgcache-expiry-timeout-ms: 60000
    eviction-interval-timer-in-ms: 30000 #服务器迁移间隔时间
    peer-eureka-nodes-update-interval-ms: 15000 #eureka所有节点更新间隔
    renewal-threshold-update-interval-ms: 30000 #更新阈值更新间隔
    wait-time-in-ms-when-sync-empty: 0 #当同步为空时的等待时间